[project]
name = "day1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "google-adk[a2a]>=1.18.0",
    "ipython>=9.7.0",
    "uvicorn>=0.38.0",
]
